#!/usr/bin/env python
import logging

import click
from firstGraphProject.model.graph import Graph
from firstGraphProject.parse_write.parser import Parser
from firstGraphProject.parse_write.writer import Writer

console = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console.setFormatter(formatter)
LOG = logging.getLogger("carlosmatos")
LOG.addHandler(console)
LOG.setLevel(logging.INFO)


@click.command()
@click.option('--parse', default='', prompt="Please enter graphs tgf file´s location for parsing:")
@click.option('--write', default='', prompt="Please enter the graphs tgf file´s location:")
def main(parse, write):
    LOG.info("""
    ________                    .__   __________                                   
 /  _____/___________  ______ |  |__\______   \_____ _______  ______ ___________ 
/   \  __\_  __ \__  \ \____ \|  |  \|     ___/\__  \\_  __ \/  ___// __ \_  __ \
\    \_\  \  | \// __ \|  |_> >   Y  \    |     / __ \|  | \/\___ \\  ___/|  | \/
 \______  /__|  (____  /   __/|___|  /____|    (____  /__|  /____  >\___  >__|   
        \/           \/|__|        \/               \/           \/     \/      
     """)
    graph = Graph()
    parser = Parser()
    writer = Writer()
    parser.parse_tgf_file(graph, parse.__str__())
    writer.write_to_tgf(graph, write)


if __name__ == "__main__":
    main()
